/**
 * American FutureTech — Client Permissions Matrix & Role Presets
 */

export const ALL_PERMISSIONS = [
  'DASHBOARD_VIEW',
  'HOMEPAGE_VIEW',
  'HOMEPAGE_EDIT',
  'COURSES_VIEW',
  'COURSES_CREATE',
  'COURSES_EDIT',
  'COURSES_DELETE',
  'PROGRAMS_VIEW',
  'PROGRAMS_CREATE',
  'PROGRAMS_EDIT',
  'PROGRAMS_DELETE',
  'JOBS_VIEW',
  'JOBS_CREATE',
  'JOBS_EDIT',
  'JOBS_DELETE',
  'FAQ_VIEW',
  'FAQ_CREATE',
  'FAQ_EDIT',
  'FAQ_DELETE',
  'CAPSTONE_VIEW',
  'CAPSTONE_CREATE',
  'CAPSTONE_EDIT',
  'CAPSTONE_DELETE',
  'MEDIA_VIEW',
  'MEDIA_UPLOAD',
  'MEDIA_EDIT',
  'MEDIA_DELETE',
  'COMPANY_LOGOS_VIEW',
  'COMPANY_LOGOS_CREATE',
  'COMPANY_LOGOS_EDIT',
  'COMPANY_LOGOS_DELETE',
  'CERTIFICATIONS_VIEW',
  'CERTIFICATIONS_CREATE',
  'CERTIFICATIONS_EDIT',
  'CERTIFICATIONS_DELETE',
  'STUDENTS_VIEW',
  'STUDENTS_EDIT',
  'STUDENTS_DELETE',
  'LEADS_VIEW',
  'LEADS_EDIT',
  'LEADS_DELETE',
  'LEADS_EXPORT',
  'ANALYTICS_VIEW',
  'SETTINGS_VIEW',
  'SETTINGS_EDIT',
  'ADMIN_MANAGEMENT_VIEW',
  'ADMIN_MANAGEMENT_CREATE',
  'ADMIN_MANAGEMENT_EDIT',
  'ADMIN_MANAGEMENT_DELETE',
  'AUDIT_LOG_VIEW',
];

export const PERMISSION_MODULES = [
  {
    id: 'dashboard',
    label: 'Dashboard & Telemetry',
    permissions: [
      { id: 'DASHBOARD_VIEW', label: 'View Dashboard' },
    ],
  },
  {
    id: 'homepage',
    label: 'Homepage CMS',
    permissions: [
      { id: 'HOMEPAGE_VIEW', label: 'View Homepage CMS' },
      { id: 'HOMEPAGE_EDIT', label: 'Edit Homepage Sections' },
    ],
  },
  {
    id: 'courses',
    label: 'Courses & Curricula',
    permissions: [
      { id: 'COURSES_VIEW', label: 'View Courses' },
      { id: 'COURSES_CREATE', label: 'Create Courses' },
      { id: 'COURSES_EDIT', label: 'Edit Courses' },
      { id: 'COURSES_DELETE', label: 'Delete Courses' },
    ],
  },
  {
    id: 'programs',
    label: 'Career Programs & Batches',
    permissions: [
      { id: 'PROGRAMS_VIEW', label: 'View Batches' },
      { id: 'PROGRAMS_CREATE', label: 'Create Batches' },
      { id: 'PROGRAMS_EDIT', label: 'Edit Batches' },
      { id: 'PROGRAMS_DELETE', label: 'Delete Batches' },
    ],
  },
  {
    id: 'jobs',
    label: 'Partner Jobs Board',
    permissions: [
      { id: 'JOBS_VIEW', label: 'View Jobs' },
      { id: 'JOBS_CREATE', label: 'Create Jobs' },
      { id: 'JOBS_EDIT', label: 'Edit Jobs' },
      { id: 'JOBS_DELETE', label: 'Delete Jobs' },
    ],
  },
  {
    id: 'faqs',
    label: 'FAQs & Blogs Content',
    permissions: [
      { id: 'FAQ_VIEW', label: 'View Content' },
      { id: 'FAQ_CREATE', label: 'Create Content' },
      { id: 'FAQ_EDIT', label: 'Edit Content' },
      { id: 'FAQ_DELETE', label: 'Delete Content' },
    ],
  },
  {
    id: 'capstone',
    label: 'Capstone & Sandboxes',
    permissions: [
      { id: 'CAPSTONE_VIEW', label: 'View Capstones' },
      { id: 'CAPSTONE_CREATE', label: 'Create Capstones' },
      { id: 'CAPSTONE_EDIT', label: 'Edit Capstones' },
      { id: 'CAPSTONE_DELETE', label: 'Delete Capstones' },
    ],
  },
  {
    id: 'media',
    label: 'Media & Upload Pipeline',
    permissions: [
      { id: 'MEDIA_VIEW', label: 'View Media' },
      { id: 'MEDIA_UPLOAD', label: 'Upload Assets' },
      { id: 'MEDIA_EDIT', label: 'Edit Media' },
      { id: 'MEDIA_DELETE', label: 'Delete Media' },
    ],
  },
  {
    id: 'logos',
    label: 'Company Logos & Partners',
    permissions: [
      { id: 'COMPANY_LOGOS_VIEW', label: 'View Logos' },
      { id: 'COMPANY_LOGOS_CREATE', label: 'Add Logos' },
      { id: 'COMPANY_LOGOS_EDIT', label: 'Edit Logos' },
      { id: 'COMPANY_LOGOS_DELETE', label: 'Delete Logos' },
    ],
  },
  {
    id: 'certifications',
    label: 'Certifications',
    permissions: [
      { id: 'CERTIFICATIONS_VIEW', label: 'View Certs' },
      { id: 'CERTIFICATIONS_CREATE', label: 'Issue Certs' },
      { id: 'CERTIFICATIONS_EDIT', label: 'Edit Certs' },
      { id: 'CERTIFICATIONS_DELETE', label: 'Revoke Certs' },
    ],
  },
  {
    id: 'students',
    label: 'Enrolled Students & LMS',
    permissions: [
      { id: 'STUDENTS_VIEW', label: 'View Students' },
      { id: 'STUDENTS_EDIT', label: 'Edit Students' },
      { id: 'STUDENTS_DELETE', label: 'Delete Students' },
    ],
  },
  {
    id: 'leads',
    label: 'Admissions Leads CRM',
    permissions: [
      { id: 'LEADS_VIEW', label: 'View Leads' },
      { id: 'LEADS_EDIT', label: 'Update Leads' },
      { id: 'LEADS_DELETE', label: 'Delete Leads' },
      { id: 'LEADS_EXPORT', label: 'Export CSV' },
    ],
  },
  {
    id: 'analytics',
    label: 'Business Analytics',
    permissions: [
      { id: 'ANALYTICS_VIEW', label: 'View Analytics' },
    ],
  },
  {
    id: 'settings',
    label: 'Settings & Config',
    permissions: [
      { id: 'SETTINGS_VIEW', label: 'View Settings' },
      { id: 'SETTINGS_EDIT', label: 'Update Settings' },
    ],
  },
  {
    id: 'admin_management',
    label: 'Admin Management',
    permissions: [
      { id: 'ADMIN_MANAGEMENT_VIEW', label: 'View Staff' },
      { id: 'ADMIN_MANAGEMENT_CREATE', label: 'Create Admin' },
      { id: 'ADMIN_MANAGEMENT_EDIT', label: 'Edit Admin' },
      { id: 'ADMIN_MANAGEMENT_DELETE', label: 'Delete Admin' },
    ],
  },
  {
    id: 'audit_log',
    label: 'System Audit Log',
    permissions: [
      { id: 'AUDIT_LOG_VIEW', label: 'View Audit Log' },
    ],
  },
];

export const ROLE_PRESETS = [
  {
    name: 'Full Admin (Everything except SuperAdmin control)',
    permissions: ALL_PERMISSIONS.filter(p => !p.startsWith('ADMIN_MANAGEMENT_DELETE')),
  },
  {
    name: 'Content & Marketing Editor',
    permissions: [
      'DASHBOARD_VIEW',
      'HOMEPAGE_VIEW',
      'HOMEPAGE_EDIT',
      'COURSES_VIEW',
      'COURSES_EDIT',
      'JOBS_VIEW',
      'JOBS_EDIT',
      'FAQ_VIEW',
      'FAQ_CREATE',
      'FAQ_EDIT',
      'FAQ_DELETE',
      'CAPSTONE_VIEW',
      'CAPSTONE_EDIT',
      'MEDIA_VIEW',
      'MEDIA_UPLOAD',
      'COMPANY_LOGOS_VIEW',
      'COMPANY_LOGOS_CREATE',
      'COMPANY_LOGOS_EDIT',
    ],
  },
  {
    name: 'Career & Placement Officer',
    permissions: [
      'DASHBOARD_VIEW',
      'JOBS_VIEW',
      'JOBS_CREATE',
      'JOBS_EDIT',
      'JOBS_DELETE',
      'LEADS_VIEW',
      'LEADS_EDIT',
      'STUDENTS_VIEW',
      'COMPANY_LOGOS_VIEW',
      'COMPANY_LOGOS_CREATE',
      'COMPANY_LOGOS_EDIT',
    ],
  },
  {
    name: 'Admissions Counselor',
    permissions: [
      'DASHBOARD_VIEW',
      'LEADS_VIEW',
      'LEADS_EDIT',
      'LEADS_EXPORT',
      'STUDENTS_VIEW',
      'COURSES_VIEW',
      'PROGRAMS_VIEW',
    ],
  },
  {
    name: 'Read-Only Auditor',
    permissions: [
      'DASHBOARD_VIEW',
      'HOMEPAGE_VIEW',
      'COURSES_VIEW',
      'PROGRAMS_VIEW',
      'JOBS_VIEW',
      'FAQ_VIEW',
      'CAPSTONE_VIEW',
      'MEDIA_VIEW',
      'COMPANY_LOGOS_VIEW',
      'CERTIFICATIONS_VIEW',
      'STUDENTS_VIEW',
      'LEADS_VIEW',
      'ANALYTICS_VIEW',
      'SETTINGS_VIEW',
      'AUDIT_LOG_VIEW',
    ],
  },
];
