/**
 * Alumni success stories used by the seeder and by scripts/seed-success-stories.cjs.
 *
 * The public /success-stories page renders every story here as a card, so the
 * list is deliberately wide (50+) — the client asked for a full alumni wall
 * instead of the original three-card sample. Fields match server/models/
 * SuccessStory.js exactly (studentName / testimonial / photo / course /
 * salaryHikePercent), the same shape the admin ContentCMS posts.
 *
 * `rating` must stay an integer: the card renders one star per unit and
 * Array(4.5) throws.
 */

// The three original stories, kept first so the seeded order never changes.
const legacyStories = [
  {
    studentName: 'Priya Sharma',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    course: 'Data Science with AI Integration',
    role: 'AI Engineer',
    company: 'Microsoft',
    salaryHikePercent: 145,
    testimonial: 'The capstone projects and mentor code reviews transformed my understanding of machine learning. The career support team conducted 4 rigorous mock interviews that directly helped me crack Microsoft!',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Marcus Bennett',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    course: 'Cyber Security with Ethical Hacking',
    role: 'Security Operations Analyst',
    company: 'Palo Alto Networks',
    salaryHikePercent: 120,
    testimonial: 'Coming from non-tech retail, American FutureTech gave me real hands-on penetration testing experience. Within 3 weeks of graduation, I received two job offers in cybersecurity!',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Daniel Chen',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    course: 'Advanced Generative & Agentic AI Master Program',
    role: 'Senior LLM Systems Engineer',
    company: 'Amazon Web Services (AWS)',
    salaryHikePercent: 160,
    testimonial: 'Agentic AI is moving fast, and this is the only program that taught LangGraph, multi-agent frameworks, and vector architectures at a true production engineering level.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
];

// 50 further alumni, grouped by program. Photos come from randomuser.me —
// stable portrait URLs, one per person — and the card falls back to the model
// default if one ever fails to load.
const alumniStories = [
  {
    studentName: 'Aarav Mehta',
    photo: 'https://randomuser.me/api/portraits/men/12.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Data Scientist',
    company: 'Capital One',
    salaryHikePercent: 138,
    testimonial: 'I moved from a support desk into a data science team in five months. The weekly mentor reviews on my fraud-detection capstone were the exact talking points that won the interview panel over.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Sophia Ramirez',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Machine Learning Engineer',
    company: 'NVIDIA',
    salaryHikePercent: 152,
    testimonial: 'The GPU acceleration labs and model-optimization modules were far beyond anything I had seen in self-paced courses. I now ship inference pipelines that serve production traffic every day.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Ethan Brooks',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Analytics Engineer',
    company: 'Walmart Global Tech',
    salaryHikePercent: 118,
    testimonial: 'Coming from a finance reporting role, the SQL and dbt-style pipeline work in the program gave me a portfolio that actually proved I could build, not just analyse.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Neha Kulkarni',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Senior Data Analyst',
    company: 'UnitedHealth Group',
    salaryHikePercent: 104,
    testimonial: 'The statistics refreshers and experimentation design module were exactly what my healthcare analytics interviews asked about. I was promoted within one quarter of finishing.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Jamal Wright',
    photo: 'https://randomuser.me/api/portraits/men/86.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Machine Learning Engineer',
    company: 'Databricks',
    salaryHikePercent: 164,
    testimonial: 'Nine months ago I was writing Excel macros. The lakehouse capstone and the interview defense panel are the two things I credit for a senior-track ML offer.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Emily Zhao',
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Data Science Manager',
    company: 'Adobe',
    salaryHikePercent: 129,
    testimonial: 'The leadership sessions on translating model output for executives changed how I present. I now lead a team of four analysts and own the experimentation roadmap.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Andre Baptiste',
    photo: 'https://randomuser.me/api/portraits/men/46.jpg',
    course: 'Data Science with AI Integration Program',
    role: 'Applied Scientist',
    company: 'Qualcomm',
    salaryHikePercent: 167,
    testimonial: 'Writing a real paper-style capstone report with mentor review is what separated my application from the hundreds of bootcamp certificates. Worth every weekend of work.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Rohan Iyer',
    photo: 'https://randomuser.me/api/portraits/men/54.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'Penetration Tester',
    company: 'CrowdStrike',
    salaryHikePercent: 141,
    testimonial: 'The Burp Suite and Active Directory attack labs were close to what I now do for clients. I walked into my pentest interview with 14 documented findings from the course range.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Grace Okafor',
    photo: 'https://randomuser.me/api/portraits/women/57.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'Security Analyst',
    company: 'IBM',
    salaryHikePercent: 112,
    testimonial: 'I had zero Linux background on day one. By the end I was comfortable in Kali, reading packet captures, and explaining risk in plain English to a hiring manager.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Lucas Moreau',
    photo: 'https://randomuser.me/api/portraits/men/18.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'Application Security Engineer',
    company: 'Shopify',
    salaryHikePercent: 147,
    testimonial: 'The secure code review module is the reason I now sit with developers instead of auditing them. My team shipped a 60% drop in critical findings after my first two quarters.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Hana Suzuki',
    photo: 'https://randomuser.me/api/portraits/women/35.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'SOC Analyst Tier II',
    company: 'Palo Alto Networks',
    salaryHikePercent: 108,
    testimonial: 'The blue-team labs, MITRE ATT&CK mapping drills and on-call style incident simulators prepared me for a live SOC rotation almost immediately.',
    rating: 4,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Diego Alvarez',
    photo: 'https://randomuser.me/api/portraits/men/45.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'Red Team Operator',
    company: 'Booz Allen Hamilton',
    salaryHikePercent: 156,
    testimonial: 'The adversary-simulation capstone became the centrepiece of my portfolio. My current lead told me afterwards it read like a real engagement report.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Priyanka Nair',
    photo: 'https://randomuser.me/api/portraits/women/79.jpg',
    course: 'Cyber Security with Ethical Hacking Program',
    role: 'Vulnerability Researcher',
    company: 'Cisco',
    salaryHikePercent: 133,
    testimonial: 'A mentor spent three Saturdays teaching me exploit development from first principles. I have since filed four responsible-disclosure reports.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Omar Haddad',
    photo: 'https://randomuser.me/api/portraits/men/23.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'AI Security Engineer',
    company: 'Microsoft',
    salaryHikePercent: 162,
    testimonial: 'Prompt-injection defence and model red-teaming were brand new to me. Six weeks after the program I was running our first LLM threat model for a customer-facing assistant.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Chloe Bennett',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'Threat Detection Engineer',
    company: 'Splunk',
    salaryHikePercent: 128,
    testimonial: 'The anomaly-detection classifiers I built in class are still the ones my team runs in production. Nothing else I studied connected security telemetry to model output this well.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Arjun Desai',
    photo: 'https://randomuser.me/api/portraits/men/67.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'Security Data Scientist',
    company: 'Fortinet',
    salaryHikePercent: 145,
    testimonial: 'Combining SIEM engineering with feature engineering for detection models opened a role that did not exist in my old company. The dual skill set is the whole point.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Maya Thompson',
    photo: 'https://randomuser.me/api/portraits/women/90.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'Adversarial ML Engineer',
    company: 'Cloudflare',
    salaryHikePercent: 171,
    testimonial: 'I came in as a backend developer and left able to break and harden a production classifier. The mentor for this track genuinely reads like a practising researcher.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Vikram Rathore',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'SOC Automation Engineer',
    company: 'Accenture',
    salaryHikePercent: 121,
    testimonial: 'Automating tier-1 triage with an ML classifier cut our alert backlog in half. I proposed it two months into the job based on my capstone.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Isabella Rossi',
    photo: 'https://randomuser.me/api/portraits/women/48.jpg',
    course: 'Cyber Security & Artificial Intelligence Program',
    role: 'Senior Security Analyst',
    company: 'Okta',
    salaryHikePercent: 136,
    testimonial: 'Identity-attack detection plus a machine-learning layer was the exact intersection my new team was hiring for. The career team rehearsed that story with me until it landed.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Nathan Cole',
    photo: 'https://randomuser.me/api/portraits/men/71.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'AI Engineer',
    company: 'Google',
    salaryHikePercent: 168,
    testimonial: 'Retrieval evaluation, chunking strategy and reranking were treated as first-class engineering problems here — that is exactly what my current team expects from day one.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Sneha Reddy',
    photo: 'https://randomuser.me/api/portraits/women/21.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'LLM Engineer',
    company: 'Salesforce',
    salaryHikePercent: 155,
    testimonial: 'The multi-agent orchestration project with tool calling is still the demo I show in interviews. The mentor feedback on failure modes was worth the entire fee.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Daniel Osei',
    photo: 'https://randomuser.me/api/portraits/men/38.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'GenAI Solutions Architect',
    company: 'ServiceNow',
    salaryHikePercent: 149,
    testimonial: 'Designing an end-to-end agent platform — ingestion, vector store, guardrails, cost controls — gave me the architecture vocabulary that senior interviews demand.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Laura Kim',
    photo: 'https://randomuser.me/api/portraits/women/63.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'Applied AI Engineer',
    company: 'Uber',
    salaryHikePercent: 143,
    testimonial: 'I was a mid-level backend engineer and am now the person my org calls for retrieval architecture. The live cohort energy kept me accountable through the hard weeks.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Faisal Khan',
    photo: 'https://randomuser.me/api/portraits/men/90.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'RAG Platform Engineer',
    company: 'Snowflake',
    salaryHikePercent: 158,
    testimonial: 'Vector database tuning, hybrid search and latency budgets are the daily job here. Almost every lab in the program mapped directly to a task I now own.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Elena Petrova',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'AI Automation Engineer',
    company: 'Stripe',
    salaryHikePercent: 131,
    testimonial: 'Building an agent that actually completes a workflow — not just chats — is what changed my career. I shipped my capstone into a real internal tool within a month.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Karan Malhotra',
    photo: 'https://randomuser.me/api/portraits/men/61.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'Senior AI Engineer',
    company: 'Meta',
    salaryHikePercent: 176,
    testimonial: 'The evaluation harness work — offline metrics, regression suites for prompts — is the part nobody teaches and the part that got me the offer.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Wei Zhang',
    photo: 'https://randomuser.me/api/portraits/women/55.jpg',
    course: 'Advanced RAG, Generative & Agentic AI Program',
    role: 'Machine Learning Engineer',
    company: 'AMD',
    salaryHikePercent: 160,
    testimonial: 'Serving LLMs efficiently on constrained hardware was my capstone, and it is now my full-time job. The mentorship on profiling was genuinely senior-level.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Rachel Adeyemi',
    photo: 'https://randomuser.me/api/portraits/women/33.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'DevOps Engineer',
    company: 'Amazon Web Services (AWS)',
    salaryHikePercent: 144,
    testimonial: 'Terraform, multi-stage Docker builds and a real CI/CD pipeline took me from manual deploys to owning infrastructure for a product team of twenty.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Tomas Novak',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Platform Engineer',
    company: 'Shopify',
    salaryHikePercent: 152,
    testimonial: 'The GitOps and progressive-delivery labs are exactly what my platform team runs. I passed the practical interview without extra prep.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Aisha Rahman',
    photo: 'https://randomuser.me/api/portraits/women/71.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Site Reliability Engineer',
    company: 'Datadog',
    salaryHikePercent: 159,
    testimonial: 'SLOs, error budgets and observability dashboards were new vocabulary for me. I now run the reliability review for a service handling millions of requests a day.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Brandon Lewis',
    photo: 'https://randomuser.me/api/portraits/men/49.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Cloud Solutions Architect',
    company: 'Oracle',
    salaryHikePercent: 137,
    testimonial: 'The cost-optimization and multi-cloud design modules gave me the confidence to lead customer workshops. I moved from support into a pre-sales architecture role.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Meera Joshi',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Kubernetes Engineer',
    company: 'Red Hat',
    salaryHikePercent: 128,
    testimonial: 'Debugging a broken cluster in the labs, with a mentor watching over screen share, is how I learned. That muscle memory got me through the toughest round of my interview.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Victor Santos',
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Infrastructure Automation Engineer',
    company: 'Siemens',
    salaryHikePercent: 122,
    testimonial: 'Automating an industrial data pipeline end to end was my capstone. My employer funded the program after seeing the first release notes I wrote from it.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Hannah Fischer',
    photo: 'https://randomuser.me/api/portraits/women/52.jpg',
    course: 'DevOps, & Cloud Computing with AI Program',
    role: 'Cloud Engineer',
    company: 'Bosch',
    salaryHikePercent: 134,
    testimonial: 'I switched from QA to cloud engineering in under a year. The structured weekend schedule meant I never had to choose between the program and my job.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Aditya Rao',
    photo: 'https://randomuser.me/api/portraits/men/83.jpg',
    course: 'AI Product Manager Program',
    role: 'AI Product Manager',
    company: 'Adobe',
    salaryHikePercent: 146,
    testimonial: 'Learning to write model evaluation criteria into a PRD is what made engineers finally trust my roadmap. The mentor sessions on stakeholder alignment were gold.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Julia Sanders',
    photo: 'https://randomuser.me/api/portraits/women/40.jpg',
    course: 'AI Product Manager Program',
    role: 'Technical Product Manager',
    company: 'Intuit',
    salaryHikePercent: 138,
    testimonial: 'As a business analyst I struggled to be taken seriously on technical products. Building a working prototype in the program changed that conversation completely.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Yusuf Demir',
    photo: 'https://randomuser.me/api/portraits/men/6.jpg',
    course: 'AI Product Manager Program',
    role: 'Product Owner',
    company: 'Salesforce',
    salaryHikePercent: 119,
    testimonial: 'The cost and latency trade-off framework we used in class is now something I present to leadership every quarter. Practical, not theoretical.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Camila Duarte',
    photo: 'https://randomuser.me/api/portraits/women/60.jpg',
    course: 'AI Product Manager Program',
    role: 'Senior Product Manager',
    company: 'Target',
    salaryHikePercent: 151,
    testimonial: 'I launched an AI-assisted search feature three months after graduating, using the experimentation plan I wrote as my capstone. It is still my strongest interview story.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Ryan Patel',
    photo: 'https://randomuser.me/api/portraits/men/41.jpg',
    course: 'AI Product Manager Program',
    role: 'AI Product Lead',
    company: 'Zoom',
    salaryHikePercent: 157,
    testimonial: 'The governance and evaluation module is what got me hired over candidates with more years. Being able to talk about model risk made the difference.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Nadia Choudhury',
    photo: 'https://randomuser.me/api/portraits/women/17.jpg',
    course: 'Governance, Risk and Compliance with AI Program',
    role: 'GRC Analyst',
    company: 'Deloitte',
    salaryHikePercent: 113,
    testimonial: 'The control-mapping exercises and audit simulation gave me a head start in my first client engagement. My manager said I onboarded faster than any analyst she had trained.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Samuel Reed',
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
    course: 'Governance, Risk and Compliance with AI Program',
    role: 'AI Governance Lead',
    company: 'EY',
    salaryHikePercent: 132,
    testimonial: 'Writing an AI risk register for a mock enterprise was the exact deliverable my current role demands. I led our first AI policy review within six months.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Ananya Bose',
    photo: 'https://randomuser.me/api/portraits/women/84.jpg',
    course: 'Governance, Risk and Compliance with AI Program',
    role: 'Compliance Engineer',
    company: 'Visa',
    salaryHikePercent: 125,
    testimonial: 'Automating evidence collection for controls was a skill I did not know was marketable. The program bridged policy work and scripting in a way nothing else did.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Gabriel Mendes',
    photo: 'https://randomuser.me/api/portraits/men/58.jpg',
    course: 'Governance, Risk and Compliance with AI Program',
    role: 'Risk & Controls Analyst',
    company: 'JPMorgan Chase',
    salaryHikePercent: 127,
    testimonial: 'Model risk documentation and audit readiness are daily realities here. The program prepared me for both, and the mentor feedback on my writing was unusually detailed.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Tara Whitfield',
    photo: 'https://randomuser.me/api/portraits/women/29.jpg',
    course: 'Governance, Risk and Compliance with AI Program',
    role: 'Security Compliance Specialist',
    company: 'Mastercard',
    salaryHikePercent: 141,
    testimonial: 'I came from a regulatory background with no technical depth. Mapping AI risks to framework controls is now the core of my job, and I understand the engineering underneath.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Nikhil Sharma',
    photo: 'https://randomuser.me/api/portraits/men/2.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Data Engineer',
    company: 'Bank of America',
    salaryHikePercent: 148,
    testimonial: 'Spark internals, partitioning and data-quality checks were taught with production constraints in mind. I built the pipeline that replaced three manual team processes.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Olivia Grant',
    photo: 'https://randomuser.me/api/portraits/women/73.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Big Data Engineer',
    company: 'Snowflake',
    salaryHikePercent: 154,
    testimonial: 'The warehouse modelling module gave me a mental model I still use every week. My hiring manager said my capstone read like an internal design doc.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2024',
  },
  {
    studentName: 'Hassan Al-Farsi',
    photo: 'https://randomuser.me/api/portraits/men/34.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Streaming Data Engineer',
    company: 'Confluent',
    salaryHikePercent: 139,
    testimonial: 'Kafka, exactly-once semantics and backpressure handling were covered in depth. I went from batch-only experience to owning a real-time pipeline in one quarter.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Divya Menon',
    photo: 'https://randomuser.me/api/portraits/women/11.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Analytics Engineer',
    company: 'Humana',
    salaryHikePercent: 117,
    testimonial: 'The program filled the gap between SQL reporting and real engineering. I now maintain the semantic layer twelve analysts depend on.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
  {
    studentName: 'Peter Lindqvist',
    photo: 'https://randomuser.me/api/portraits/men/79.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Data Platform Engineer',
    company: 'MongoDB',
    salaryHikePercent: 143,
    testimonial: 'Schema design at scale, sharding trade-offs and CDC pipelines — every lab felt like a ticket from a real backlog. I moved into a platform role within four months.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2026',
  },
  {
    studentName: 'Simran Kaur',
    photo: 'https://randomuser.me/api/portraits/women/65.jpg',
    course: 'Big Data & Data Engineering Fundamentals Program',
    role: 'Senior Data Engineer',
    company: 'Cognizant',
    salaryHikePercent: 109,
    testimonial: 'The mentors insisted on tests and CI for data pipelines, which nobody around me was doing. That habit is the reason I was promoted to senior within the year.',
    rating: 5,
    isFeatured: true,
    graduationYear: '2025',
  },
];

const successStoriesSeed = [...legacyStories, ...alumniStories];

module.exports = { successStoriesSeed, legacyStories, alumniStories };
